version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - docker build -t backend-app .
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
